### ISSUE TITLE
When will the training code be released?

### ISSUE THREAD

**Issue by Hoteryoung** [VicenteVivan/geo-clip#1]
Dear author,
I'm interested in your project and I want to know when the training code will be released. Thanks.

**Comment by VicenteVivan** [comment]
Hi Hunter,

Thank you for your interest in our project. We have recently added a simple training loop with the required methods to run it. We will update the training code in the upcoming days, including detailed instructions and quick access via the API.

Please let me know if you have any questions or suggestions.

Sincerely,
Vicente
