### ISSUE TITLE
Thoughts on using Cartesian Coordinates instead of EEP

### ISSUE THREAD

**Issue by Larry-Gan** [VicenteVivan/geo-clip#12]
Hello, this paper here: https://arxiv.org/pdf/2405.14702v1 claimed that using Cartesian Coordinates instead of EEP improved the performance of their models. Are there any plans on implementing that in this repo as well?

**Comment by VicenteVivan** [comment]
Hi Larry,

Thank you for your question.

We initially experimented with various coordinate systems, including Cartesian coordinates. During these tests, we found that the Equal Earth Projection consistently yielded better model performance, leading us to select it for our implementation.

Given these results, we do not plan to integrate Cartesian coordinates into this repository. However, if you wish to explore this option, modifying the code to use Cartesian coordinates is straightforward. Keep in mind that doing so would require re-training the model, and based on our findings, it may not offer any performance advantage in this specific context.

Sincerely,
Vicente
