### ISSUE TITLE
Where can I get training data?

### ISSUE THREAD

**Issue by kig1929** [VicenteVivan/geo-clip#2]
Dear author.
Thank you for sharing interesting research.

I'm trying to download the training data in the paper(MP-16), but I can't find it on the official website. 
http://www.multimediaeval.org/mediaeval2016/placing/
Can you please give me a link?

**Comment by VicenteVivan** [comment]
Hi Kig,

Thank you for reaching out. The training data for MP-16 is available in the [GitHub repo](https://github.com/shramanpramanick/transformer_based_geo-localization) associated with the paper by Shraman Pramanick et al., _"Where in the world is this image? Transformer-based geo-localization in the wild."_ You'll find the training dataset download instructions there.

Best,
Vicente
