### ISSUE TITLE
When will the testing code be released?

### ISSUE THREAD

**Issue by DoubenDo** [VicenteVivan/geo-clip#5]
Dear author,
Great work! I have recently been developing a new model to solve the same task and would like to have your TESTING code to test the performance of my model.

I would appreciate your generosity. Looking forward to your response, thank you.

**Comment by VicenteVivan** [comment]
Hi Douben,

Thank you for your patience and kind words. We have just added a script to evaluate the performance of GeoCLIP. Please, let us know if you have any more questions or suggestions.
